# shellcheck shell=bash

export TMUX_POWERLINE_DEBUG_MODE_ENABLED="false"
export TMUX_POWERLINE_ERROR_LOGS_ENABLED="false"
export TMUX_POWERLINE_ERROR_LOGS_SCOPES=""
export TMUX_POWERLINE_PATCHED_FONT_IN_USE="true"

export TMUX_POWERLINE_THEME="ben-minimal"
export TMUX_POWERLINE_DIR_USER_THEMES="${XDG_CONFIG_HOME:-$HOME/.config}/tmux-powerline/themes"
export TMUX_POWERLINE_DIR_USER_SEGMENTS="${XDG_CONFIG_HOME:-$HOME/.config}/tmux-powerline/segments"

export TMUX_POWERLINE_STATUS_VISIBILITY="2"
export TMUX_POWERLINE_WINDOW_STATUS_LINE=0
export TMUX_POWERLINE_STATUS_INTERVAL="1"
export TMUX_POWERLINE_STATUS_JUSTIFICATION="centre"
export TMUX_POWERLINE_STATUS_LEFT_LENGTH="60"
export TMUX_POWERLINE_STATUS_RIGHT_LENGTH="90"
export TMUX_POWERLINE_WINDOW_STATUS_SEPARATOR=""

export TMUX_POWERLINE_SEG_PANE_STATUS_LABEL="panes"
export TMUX_POWERLINE_SEG_PWD_MAX_LEN="40"
export TMUX_POWERLINE_SEG_VCS_BRANCH_MAX_LEN=""
export TMUX_POWERLINE_SEG_VCS_BRANCH_DEFAULT_SYMBOL="branch"
export TMUX_POWERLINE_SEG_VCS_BRANCH_GIT_SYMBOL_COLOUR="5"
export TMUX_POWERLINE_SEG_VCS_BRANCH_HG_SYMBOL_COLOUR="45"
export TMUX_POWERLINE_SEG_VCS_BRANCH_SVN_SYMBOL_COLOUR="220"
