unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -g mouse on
set -g history-limit 10000

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'azorng/tmux-smooth-scroll'
set -g @plugin 'Nucc/tmux-which-key'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'laktak/extrakto'
set -g @extrakto_clip_mode 'tmux_osc52'
set -g @extrakto_clip_mode_order 'tmux_osc52 buffer'
set -g @plugin 'omerxx/tmux-floax'
set -g @plugin 'erikw/tmux-powerline'

run '~/.tmux/plugins/tpm/tpm'

bind-key -T copy-mode WheelUpPane send-keys -X -N 1 scroll-up
bind-key -T copy-mode WheelDownPane send-keys -X -N 1 scroll-down
