unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Inactive panes: dim fg (comment), slightly darker bg
set -g window-style 'fg=#6272a4,bg=#21222c'

# Active pane: full Dracula fg + default bg
set -g window-active-style 'fg=#f8f8f2,bg=#282a36'

# Make the border colors match too
set -g pane-border-style 'fg=#44475a'
set -g pane-active-border-style 'fg=#bd93f9'

#set -g window-style 'fg=colour244'
#set -g window-active-style 'fg=colour255'

set -g mouse on
set -g history-limit 10000
set -g pane-border-status top
set -g pane-border-format " #{pane_index}: #{pane_title} "

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'azorng/tmux-smooth-scroll'
set -g @plugin 'Nucc/tmux-which-key'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'laktak/extrakto'
set -g @extrakto_clip_mode 'tmux_osc52'
set -g @extrakto_clip_mode_order 'tmux_osc52 buffer'
set -g @plugin 'omerxx/tmux-floax'
set -g @plugin 'erikw/tmux-powerline'

run '~/.tmux/plugins/tpm/tpm'

bind-key -T copy-mode WheelUpPane send-keys -X -N 1 scroll-up
bind-key -T copy-mode WheelDownPane send-keys -X -N 1 scroll-down
